# Basic
name: metropolitan_museum_data
profile: metropolitan_museum_data
version: "1.0.0"

# Paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

flags:
  send_anonymous_usage_stats: False

clean-targets:  # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  metropolitan_museum_data:
    # Config indicated by + and applies to all files under models/example/
    staging:
      materialized: view
    core:
      materialized: table
    example:
      +materialized: view
